// TrainingArtifacts/Week-4/Day4/skills-page-in-angular/src/app/pages/landing-page/landing-page.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { ITile } from '../../tile/tile.component';


@Component({
  selector: 'app-landing-page',
  templateUrl: './landing-page.component.html',
  styleUrls: ['./landing-page.component.css']
})
export class LandingPageComponent implements OnInit {
  headerText: string;
  skillInformation: Array<ITile> = [
    {
      name: 'HTML',
      description: 'aaaa',
      imgURL: 'assets/images/html.png'
    },
    {
      name: 'CSS',
      description: 'aaaa',
      imgURL: 'assets/images/html.png'
    },
    {
      name: 'JS',
      description: 'aaaa',
      imgURL: 'assets/images/html.png'
    },
    {
      name: 'React',
      description: 'aaaa',
      imgURL: 'assets/images/html.png'
    },
    {
      name: 'Angular',
      description: 'aaaa',
      imgURL: 'assets/images/html.png'
    },
    {
      name: 'Webpack',
      description: 'aaaa',
      imgURL: 'assets/images/html.png'
    },
    {
      name: 'HTML',
      description: 'aaaa',
      imgURL: 'assets/images/html.png'
    },
    {
      name: 'CSS',
      description: 'aaaa',
      imgURL: 'assets/images/html.png'
    },
    {
      name: 'JS',
      description: 'aaaa',
      imgURL: 'assets/images/html.png'
    },
    {
      name: 'React',
      description: 'aaaa',
      imgURL: 'assets/images/html.png'
    },
    {
      name: 'Angular',
      description: 'aaaa',
      imgURL: 'assets/images/html.png'
    },
    {
      name: 'Webpack',
      description: 'aaaa',
      imgURL: 'assets/images/html.png'
    }
  ]
  constructor() {
    this.headerText = "We are learning";
  }

  ngOnInit() {
  }
}

<app-header [text]="headerText"></app-header>
<app-tile *ngFor="let tileObj of skillInformation" [tileInfo]="tileObj"></app-tile>

// TrainingArtifacts/Week-4/Day4/skills-page-in-react/src/page/landing-page.js
import React, { Component } from 'react';
import Header from '../components/header/header'
import Tile from '../components/tile/tile';

class LandingPage extends Component {
    constructor() {
        super();
        this.skillInformation = [
            {
                name: 'HTML',
                description: 'aaaa',
                imgURL: '/images/html.png'
            },
            {
                name: 'CSS',
                description: 'aaaa',
                imgURL: '/images/html.png'
            },
            {
                name: 'JS',
                description: 'aaaa',
                imgURL: '/images/html.png'
            },
            {
                name: 'React',
                description: 'aaaa',
                imgURL: '/images/html.png'
            },
            {
                name: 'Angular',
                description: 'aaaa',
                imgURL: '/images/html.png'
            },
            {
                name: 'Webpack',
                description: 'aaaa',
                imgURL: '/images/html.png'
            },
            {
                name: 'HTML',
                description: 'aaaa',
                imgURL: '/images/html.png'
            },
            {
                name: 'CSS',
                description: 'aaaa',
                imgURL: '/images/html.png'
            },
            {
                name: 'JS',
                description: 'aaaa',
                imgURL: '/images/html.png'
            },
            {
                name: 'React',
                description: 'aaaa',
                imgURL: '/images/html.png'
            },
            {
                name: 'Angular',
                description: 'aaaa',
                imgURL: '/images/html.png'
            },
            {
                name: 'Webpack',
                description: 'aaaa',
                imgURL: '/images/html.png'
            }
        ]
    }
    render() {
        return (
            <div>
                <Header text="We are learning" />
                <div className="container">
                    {this.skillInformation.map(skill => {
                        return (
                            <Tile skillName={skill.name} skillDescription={skill.description}
                                skillImg={skill.imgURL} />
                        )
                    })}
                </div>
            </div>
        );
    }
}

export default LandingPage
