// TrainingArtifacts/Week-4/Day5/weather-app-in-angular/src/app/components/summary/summary.component.ts
import { ISummary } from './../../models/summary';
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-summary',
  templateUrl: './summary.component.html',
  styleUrls: ['./summary.component.css']
})
export class SummaryComponent implements OnInit {

  @Input() summaryInfo: ISummary;
  constructor() { }

  ngOnInit() {
  }

}

<div>
  <div class="searched-place" id="searched-place">
    <span id="place">{{summaryInfo.cityName}}
    </span>
  </div>
  <div class="day" id="current-day">
    <span id="day">{{summaryInfo.day}}</span>
  </div>
  <div class="weather-condition">
    <p id="cond">{{summaryInfo.weatherCondition}}</p>
  </div>
</div>

// TrainingArtifacts/Week-5/Day1/weather-app-in-react/src/components/summary/summary.js
import React, { Component } from 'react';
import './summary.css';

function Summary(props) {
    return (
        <div>
            <div class="searched-place" id="searched-place">
                <span id="place">{props.summaryInfo.cityLocation}
                </span>
            </div>
            <div class="day" id="current-day">
                <span id="day">{props.summaryInfo.day}</span>
            </div>
            <div class="weather-condition">
                <p id="cond">{props.summaryInfo.weatherCondition}</p>
            </div>
        </div>
    )
}

export default Summary;
