// TrainingArtifacts/Week-5/Day1/weather-app-in-react/src/components/tpw/tpw.js
import React, { Component } from 'react';

class Tpw extends Component {
    render() {
        return (
            <div class="banner-right">
                <div class="row1">
                    <div class="pressure"> Pressure: <span id="pressure"> 80Hg</span></div>
                    <div class="humidity"> Humidity: <span id="humidity"> 80%</span></div>
                    <div class="wind"> Wind:<span id="wind"> 80%</span></div>
                </div>
                <div class="row2">
                    <div class="btn-group">
                        <button type="button" class="btn btn-primary">Temperature</button>
                        <button type="button" class="btn btn-primary">Pressure</button>
                        <button type="button" class="btn btn-primary">Wind</button>
                    </div>
                </div>
            </div>
        );
    }
}

export default Tpw;

// TrainingArtifacts/Week-4/Day5/weather-app-in-angular/src/app/components/tpw/tpw.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Itpw } from '../../models/tpw';

@Component({
  selector: 'app-tpw',
  templateUrl: './tpw.component.html',
  styleUrls: ['./tpw.component.css']
})
export class TpwComponent implements OnInit {

  @Input() tpwInfo: Itpw;
  constructor() { }

  ngOnInit() {
  }

}

<div class="banner-right">
  <div class="row1">
    <div class="pressure"> Temperature:
      <span id="pressure"> {{tpwInfo.temparature}}Hg</span>
    </div>
    <div class="humidity"> Pressure:
      <span id="humidity"> {{tpwInfo.pressure}}%</span>
    </div>
    <div class="wind"> Wind:
      <span id="wind"> {{tpwInfo.windSpeed}}%</span>
    </div>
  </div>
  <div class="row2">
    <div class="btn-group">
      <button type="button" class="btn btn-primary">Temperature</button>
      <button type="button" class="btn btn-primary">Pressure</button>
      <button type="button" class="btn btn-primary">Wind</button>
    </div>
  </div>
</div>
