// TrainingArtifacts/Week-4/Day5/weather-app-in-angular/src/app/components/day-tile/day-tile.component.ts
import { WeatherService } from './../../weather.service';
import { IDayTile } from './../../models/dayTile';
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-day-tile',
  templateUrl: './day-tile.component.html',
  styleUrls: ['./day-tile.component.css']
})
export class DayTileComponent implements OnInit {

  @Input() dayTileInfo: IDayTile;
  constructor(private weatherService: WeatherService) { }

  ngOnInit() {
  }

  onTileClick() {
    this.weatherService.updateDayInfoFor(this.dayTileInfo.dayNum);
  }

}

<div (click)="onTileClick()">
  <div class="col-xs-2" id="grid1">
    <p id="fday1">{{dayTileInfo.day}}</p>
    <img src="{{dayTileInfo.imageURL}}" id="fimg1" alt="image" />
    <p>
      <span id="high1">{{dayTileInfo.maxTemp}}</span>
      <sup>o</sup>
      <span id="low1">{{dayTileInfo.minTemp}}</span>
      <sup>o</sup>
    </p>
  </div>
</div>

// TrainingArtifacts/Week-5/Day1/weather-app-in-react/src/components/day-tile/day-tile.js
import React, { Component } from 'react';

function DayTile(props) {
    return (
        <div className="col-xs-3" id="grid1" >
            <p id="fday1">{props.dayInfo.day}</p>
            <img src={props.dayInfo.imageURL} id="fimg1" alt="image" />
            <p><span id="high1">{props.dayInfo.maxTemp}</span><sup>o</sup><span id="low1">{props.dayInfo.minTemp}</span><sup>o</sup></p>
        </div>
    );
}

export default DayTile;
