// TrainingArtifacts/Week-4/Day4/skills-page-in-react/src/components/tile/tile.js
import React from 'react';

function Tile(props) {
    return (
        <div className="col-lg-3 col-md-4">
            <div className="img-container">
                <img src={props.skillImg} alt={props.skillName} />
            </div>
            <div className="skill-name">
                {props.skillName}
            </div>
            <div className="skill-writeup">
                {props.skillDescription}
                {/* I will write semantic markup in HTML5 which is the latest standard of core technology of web. */}
            </div>
        </div>
    )
}

export default Tile

// TrainingArtifacts/Week-4/Day4/skills-page-in-angular/src/app/tile/tile.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-tile',
  templateUrl: './tile.component.html',
  styleUrls: ['./tile.component.css']
})
export class TileComponent implements OnInit {

  @Input() tileInfo: ITile;
  constructor() { }

  ngOnInit() {
  }

}

export interface ITile {
  name: string;
  description: string;
  imgURL: string;
} 

<div class="col-lg-3 col-md-4">
  <div class="img-container">
    <img src="{{tileInfo.imgURL}}" alt="{{tileInfo.name}}">
  </div>
  <div class="skill-name">
    {{tileInfo.name}}
  </div>
  <div class="skill-writeup">
    {{tileInfo.description}}
  </div>
</div>
